In [14]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from problems.time_series.common import trend, seasonality, noise, windowed_dataset, plot_series

tf.__version__

import typing
from tensorflow import keras

if typing.TYPE_CHECKING:
    from keras.api._v2 import keras

In [15]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)

for window_dataset in dataset:
    for var in window_dataset:
        print(var.numpy())
    print()

0
1
2
3
4

1
2
3
4
5

2
3
4
5
6

3
4
5
6
7

4
5
6
7
8

5
6
7
8
9



In [16]:
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
    print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [17]:
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
for x, y in dataset:
    print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [18]:
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(3).prefetch(1)
for x, y in dataset:
    print("___________________")
    print(x.numpy())
    print(y.numpy())
    print("___________________")

___________________
[[0 1 2 3]
 [4 5 6 7]
 [3 4 5 6]]
[[4]
 [8]
 [7]]
___________________
___________________
[[1 2 3 4]
 [2 3 4 5]
 [5 6 7 8]]
[[5]
 [6]
 [9]]
___________________
